###
POST http://127.0.0.1:8000/login/
Content-Type: application/json

{"email":"mo@gmail.com","password":"123"}

###
POST http://127.0.0.1:8000/signup/
Content-Type: application/json

{"first_name":"Moaz","last_name":"mohamed","email":"az@gmail.com","password":"123"}

###
POST http://127.0.0.1:8000/addcv/
Content-Type: application/json

{
    "cv_name":"fourth cv",
    "user_id": 1,
    "job": "driver engineer",
    "city": "giza",
    "country": "egypt",
    "email": "m@gmil.com",
    "objective": "string",
    "degree": "bechlor of cs",
    "school": "cairo uni",
    "school_department": "computer science",
    "school_city": "gize",
    "school_country": "string",
    "start_school_date": "2024-10-13T18:06:11.056Z",
    "end_school_date": "2024-10-13T18:06:11.056Z",
    "skills": [
        "hard worker",
        "team orineted"
    ],
    "projects": [
        {
            "project_name": "cv builder react",
            "project_date": "2024-10-13T18:06:11.056Z",
            "project_details": "cv builder react"
        },
        {
            "project_name": "restaurant react",
            "project_date": "2024-10-13T18:06:11.056Z",
            "project_details": "restaurant react"
        }
    ],
    "experiences": [
        {
            "job_title": "team leader",
            "start_date": "2024-10-13T18:06:11.056Z",
            "end_date": "2024-10-13T18:06:11.056Z",
            "job_description": "team leader",
            "company": "team leader"
        },
        {
            "job_title": "software intern",
            "start_date": "2024-10-13T18:06:11.056Z",
            "end_date": "2024-10-13T18:06:11.056Z",
            "job_description": "software intern",
            "company": "software intern"
        }
    ],
    "extra_curricular_activities": [
        "hamda",
        "adf",
        "afd",
        "fad"
    ]
}


###
Get http://127.0.0.1:8000/cv/1
Content-Type: application/json


###
put http://127.0.0.1:8000/editcv/
Content-Type: application/json

{
    "cv_id":"1",
    "cv_name":"7th cv",
    "user_id": 1,
    "job": "driver engineer",
    "city": "cairo",
    "country": "egypt",
    "email": "m@gmil.com",
    "objective": "string",
    "degree": "bechlor of cs",
    "school": "cairo uni",
    "school_department": "computer science",
    "school_city": "gize",
    "school_country": "string",
    "start_school_date": "2024-10-13T18:06:11.056Z",
    "end_school_date": "2024-10-13T18:06:11.056Z",
    "skills": [
        "hard worker",
        "team orineted"
    ],
    "projects": [
        {
            "project_name": "cv builder react",
            "project_date": "2024-10-13T18:06:11.056Z",
            "project_details": "cv builder react"
        },
        {
            "project_name": "restaurant react",
            "project_date": "2024-10-13T18:06:11.056Z",
            "project_details": "restaurant react"
        }
    ],
    "experiences": [
        {
            "job_title": "team leader",
            "start_date": "2024-10-13T18:06:11.056Z",
            "end_date": "2024-10-13T18:06:11.056Z",
            "job_description": "team leader",
            "company": "team leader"
        },
        {
            "job_title": "software intern",
            "start_date": "2024-10-13T18:06:11.056Z",
            "end_date": "2024-10-13T18:06:11.056Z",
            "job_description": "software intern",
            "company": "software intern"
        }
    ],
    "extra_curricular_activities": [
        "hamda",
        "adf",
        "afd",
        "fad"
    ]
}
