###
POST http://127.0.0.1:8000/login/
Content-Type: application/json

{"email":"az@gmail.com","password":"123456789"}

###
POST http://127.0.0.1:8000/signup/
Content-Type: application/json

{"first_name":"Moaz","last_name":"mohamed","email":"az@gmail.com","password":"123456789"}

###
POST http://127.0.0.1:8000/addcv/
Content-Type: application/json

{
    "cvName": "shshf cv",
    "userId": 1,
    "template":"cvtemp",
    "firstName":"ahmed",
    "lastName":"mohamed",
    "job": "driver engineer",
    "city": "giza",
    "country": "egypt",
    "email": "m@gmil.com",
    "objective": "string",
    "degree": "bechlor of cs",
    "school": "cairo uni",
    "schoolDepartment": "computer science",
    "schoolCity": "gize",
    "schoolCountry": "string",
    "startSchoolDate": "2024-10-13T18:06:11.056Z",
    "endSchoolDate": "2024-10-13T18:06:11.056Z",
    "skills": [
        "hard worker",
        "team orineted"
    ],
    "projects": [
        {
            "projectName": "cv builder react",
            "projectDate": "2024-10-13T18:06:11.056Z",
            "projectDetails": "cv builder react"
        },
        {
            "projectName": "restaurant react",
            "projectDate": "2024-10-13T18:06:11.056Z",
            "projectDetails": "restaurant react"
        }
    ],
    "experiences": [
        {
            "jobTitle": "team leader",
            "startDate": "2024-10-13T18:06:11.056Z",
            "endDate": "2024-10-13T18:06:11.056Z",
            "jobDescription": "team leader",
            "company": "team leader"
        },
        {
            "jobTitle": "software intern",
            "startDate": "2024-10-13T18:06:11.056Z",
            "endDate": "2024-10-13T18:06:11.056Z",
            "jobDescription": "software intern",
            "company": "software intern"
        }
    ],
    "extraCurricularActivities": [
        "hamda",
        "adf",
        "afd",
        "fad"
    ]
}



###
Get http://127.0.0.1:8000/usercvs/1
Content-Type: application/json

###
Get http://127.0.0.1:8000/cv/1
Content-Type: application/json


###
DELETE http://127.0.0.1:8000/deletecv/
Content-Type: application/json

{
    "userId":1,
    "cvName":"first cv"
}


###
DELETE http://127.0.0.1:8000/deleteallcvs/
Content-Type: application/json

{
    "userId":1
}


###
put http://127.0.0.1:8000/editcv/
Content-Type: application/json

{
    "cvId":1 ,
    "cvName": "first cv",
    "userId": 1,
    "template":"cvtemp",
    "firstName": "zoz",
    "lastName": "mohamed",
    "job": "driver engineer",
    "city": "giza",
    "country": "egypt",
    "email": "m@gmil.com",
    "objective": "string",
    "degree": "bechlor of cs",
    "school": "cairo uni",
    "schoolDepartment": "computer science",
    "schoolCity": "gize",
    "schoolCountry": "string",
    "startSchoolDate": "2024-10-13T18:06:11.056Z",
    "endSchoolDate": "2024-10-13T18:06:11.056Z",
    "skills": [
        "hard worker",
        "team orineted"
    ],
    "projects": [
        {
            "projectName": "cv builder react",
            "projectDate": "2024-10-13T18:06:11.056Z",
            "projectDetails": "cv builder react"
        },
        {
            "projectName": "restaurant react",
            "projectDate": "2024-10-13T18:06:11.056Z",
            "projectDetails": "restaurant react"
        }
    ],
    "experiences": [
        {
            "jobTitle": "team leader",
            "startDate": "2024-10-13T18:06:11.056Z",
            "endDate": "2024-10-13T18:06:11.056Z",
            "jobDescription": "team leader",
            "company": "team leader"
        },
        {
            "jobTitle": "software intern",
            "startDate": "2024-10-13T18:06:11.056Z",
            "endDate": "2024-10-13T18:06:11.056Z",
            "jobDescription": "software intern",
            "company": "software intern"
        }
    ],
    "extraCurricularActivities": [
        "hamda",
        "adf",
        "afd",
        "fad"
    ]
}
